services:
  - type: web
    name: my-news-website
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn MyNewsWebsite.wsgi:application"
    plan: free
    branch: main
    rootDir: Scripts/MyNewsWebsite
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: my-news-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: my-news-db
    plan: free
    databaseName: my_news
    user: my_news_user
